version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jerry.6719822
      POSTGRES_DB: nestdb
    ports:
      - 5432:5432